@baseUrl = http://localhost:8080

### OpenFGA ListObjects: All resources a user can view
POST {{$dotenv OPENFGA_API_URL}}/stores/{{$dotenv OPENFGA_STORE_ID}}/list-objects
Content-Type: application/json

{
  "type": "resource",
  "relation": "can_view_resource",
  "user": "user:bob"
}

### OpenFGA ListObjects: Organizations where a user is admin
POST {{$dotenv OPENFGA_API_URL}}/stores/{{$dotenv OPENFGA_STORE_ID}}/list-objects
Content-Type: application/json

{
  "type": "organization",
  "relation": "admin",
  "user": "user:alice"
}

### OpenFGA ListUsers: Users who can add resources to an organization
POST {{$dotenv OPENFGA_API_URL}}/stores/{{$dotenv OPENFGA_STORE_ID}}/list-users
Content-Type: application/json

{
  "object": {
    "type": "organization",
    "id": "acme"
  },
  "relation": "can_add_resource",
  "user_filters": [
    {
      "type": "user"
    }
  ]
}

### OpenFGA Check: Can a user add a member to an organization?
POST {{$dotenv OPENFGA_API_URL}}/stores/{{$dotenv OPENFGA_STORE_ID}}/check
Content-Type: application/json

{
  "tuple_key": {
    "object": "organization:acme",
    "relation": "can_add_member",
    "user": "user:alice"
  }
}
