# Requires the REST Client Extension in VSCode/Cursor: humao.rest-client
@apphost=http://localhost:5255
@daprHost=http://localhost:3500
@user_id=alice

### Create Resource
# @name startCreateTeamMemberWorkflow
POST {{daprHost}}/v1.0/workflows/dapr/grant_organization_membership_workflow/start
Content-Type: application/json

{
  "actor_id": "alice",
  "user_id": "charlie",
  "role": "member",
  "organization_id": "acme"
}

### Get the workflow status
@instanceId={{startCreateTeamMemberWorkflow.response.body.instanceID}}
### Get the workflow status
GET {{ daprHost }}/v1.0/workflows/dapr/{{ instanceId }}

### Grant permissions approved event
POST {{daprHost}}/v1.0/workflows/dapr/{{ instanceId }}/raiseEvent/manual_override_approved
Content-Type: application/json

